### PR TITLE
Add CI skip command check template

### PR DESCRIPTION
**Pull request by ConorMacBride**
Adds a template as discussed in https://github.com/sunpy/sunpy/issues/5589 which parses the merge commit message for a PR run (`Merge A into B`), extracts the latest commit hash on the PR branch (`A`) and gets its commit message. If this commit message contains a recognised CI skip command, a dependency variable is set which can be used as a condition in subsequent pipeline stages.

The parsing of the commit message is done using Bash. Most has been put in Bash functions to structure the script better and have more robust error checking.

Need to think about testing. I can test on a separate package as a one off. Testing the *template* inside this repository may not work as the template assumes that the Bash script belongs in a remote repository. At the very least, the Bash script could be tested directly in this repository's `azure-pipelines.yml`.

### CODE REVIEW

**Comment by ConorMacBride** [comment]
The template is now working in this PR https://github.com/ConorMacBride/mcalf/pull/43! Here's an [Azure run](https://dev.azure.com/ConorMacBride/mcalf/_build/results?buildId=183&view=results) triggered by pushing to the PR branch, and here's an [Azure run](https://dev.azure.com/ConorMacBride/mcalf/_build/results?buildId=186&view=results) which was triggered manually. I configured the new template to only look for skip commands if the build reason is `PullRequest`, so it doesn't affect CI runs, scheduled runs, manual runs etc.

@Cadair This is ready for review and merge, unless you want tests for the Bash script.

**Review by Cadair — APPROVED** [review]
This is wonderful, thank you so much!

**Comment by Cadair** [comment]
I am happy testing this in sunpy given the complexity lol

**Comment by Cadair** [comment]
hmmmmmmmm

image

**Comment by Cadair** [comment]
Just used this successfully on [ndcube](https://github.com/sunpy/ndcube/pull/500) it's wonderful :grinning:

**Pull request merged**
