### PR TITLE
Add caching

### PR DESCRIPTION
**Pull request by ConorMacBride**
Based on #63, this allows for a list of cached directories to be specified.

### CODE REVIEW

**Comment by Cadair** [comment]
This PR is looking great, docs and tests warm my heart :heart_eyes:

**Comment by ConorMacBride** [comment]
The caching doesn't work as I assumed so I had to adjust the way I implemented it in the template and also the testing. In particular, once a cache with a particular key is created it cannot be updated or replaced. (Although they are cleared after 7 days of inactivity.) I also added a ``docker_cache`` option to cache docker images in specific environments.

**Review by Cadair — APPROVED** [review]
Looks good to me, thanks a lot!

**Comment by Cadair** [comment]
@ConorMacBride Do you fancy trying this out on the sunpy repo? :D

**Comment by ConorMacBride** [comment]
Yeah, I'll take a look this evening.

**Comment by Cadair** [comment]
Thanks!

**Pull request merged**
